### PR TITLE
Fixes #31 [WIP] (meta tag)

### LINKED ISSUE #31: TorPaste and iOS
I do not know about other mobile operation systems, but in iOS, when visiting the page (say [this](https://paste.daknob.net/) the website shown is the full version and not the mobile one. I think this is done because iOS needs some special `<meta>` tags for the viewport. Can someone more experienced have a look and address this issue?

### PR DESCRIPTION
**Pull request by vijeth-aradhya**
I have added the meta tag and given appropriate description in the commit.

Please check if it works both on Google and on iOS platform

### CODE REVIEW

**Comment by daknob** [comment]
Hello @vijeth-aradhya . Is this PR still a `WIP`?
Thanks

**Comment by daknob** [comment]
By the way, I have tested this and it fixes #31 . Do you think there's something else to commit?

**Comment by vijeth-aradhya** [comment]
@DaKnOb Nope I don't think so. I was waiting for your response :)

**Comment by daknob** [comment]
Thanks for the Pull Request! I'm sorry I missed to review it earlier.

**Pull request merged**
