### PR TITLE
Refactor code

### PR DESCRIPTION
**Pull request by daknob**
A new file called `logic.py` has been created whose purpose is to include all application logic. This file will then be used by `torpaste.py` to make all decisions in the HTTP level using Flask.

### CODE REVIEW

**Comment by daknob** [comment]
@j11e I am proposing these changes, which may unfortunately break Pull Request #49 . If you like these changes, let me know, so we can find a solution. This is just a heads up. I think it will clean up the codebase a lot, and will help in fixing issue #19 which I will be working on after I finish with this.

**Comment by daknob** [comment]
BTW, we probably have to come up with a smarter system than the multiple returns in order to convey messages to `torpaste.py`. Exceptions sure can be one of them, however I did not implement them for simplicity. Will probably do this soon, definitely before merging.

**Comment by j11e** [comment]
I was away this week-end, I'll take a look tomorrow. No worries about the pull request anyway, I'll just rebase.

**Review by j11e — APPROVED** [review]

**Comment by j11e** [comment]
I'm ok with the changes. Fun fact: I was thinking of moving the configuration handling code in another file, considering how fast the number of supported variables is increasing. You moved out the other part of the code first :)

**Comment by daknob** [comment]
Thanks! So yes, I moved the other part as well and I am also considering moving the configuration code, but I have not done this yet. Give me some time to work on this PR a little bit more, and if everything is okay, I'll merge it and then work on Exceptions. You can work on moving the config file if you'd like.. :-)

**Pull request merged**
