### PR TITLE
#21: Add a configuration option to enable/disable paste listing

### PR DESCRIPTION
**Pull request by j11e**
I also reworked configuration a bit, for easier extension in the future (one global object instead of N global variables).

Also, I added a parameter to `initialize_backend` for backend parameters. For now, it's empty.

### CODE REVIEW

**Comment by daknob** [comment]
Hey, thanks.. So, do you think we should pass the parameters to the backend? That's an issue in my opinion because we need to make TorPaste backend-agnostic, and including the configuration parameters in the main file doesn't help. What I was thinking for backends was that `torpaste.py` will select the appropriate backend, and then the MySQL backend will look for whatever `ENV` variables it may need, such as `TP_BACKEND_MYSQL_HOST`. From what I understand, in the current setup, we need to handle everything in `torpaste.py` and then pass it in the `backend_config` to every backend. Is that correct?

**Comment by j11e** [comment]
The way I did things, yes, `torpaste.py` would handle all configuration. Your idea is actually better. I'll change that.

**Comment by j11e** [comment]
Ok, I removed the backend-specific configuration from the core. `initialize_backend` does not take a `parameters` argument anymore.

**Comment by daknob** [comment]
Merged, and commit pushed to update `README.md`.

**Pull request merged**
