### PR TITLE
refactoring and applying PEP8

### PR DESCRIPTION
**Pull request by stiefel40k**

### CODE REVIEW

**Comment by j11e** [comment]
Hi @stiefel40k!

I leave the decision to merge or not to @DaKnOb, but just a question: to follow PEP8, shouldn't the comment blocks before functions be [triple-quoted strings](https://www.python.org/dev/peps/pep-0008/#documentation-strings)?

**Comment by stiefel40k** [comment]
Hi @j11e!

Basically yes, the tripe-quated strings are "parsed" as docstrings. This means if you use an IDE like PyCharm or something like that and you hit ctrl+q it will show you that strings as documentation. I didn't change those comment blocks, because, I didn't know if you used the line comments intentionally. So if you wish, I can create you these docstings.

**Comment by j11e** [comment]
Well, I had that refactoring in mind for the future, and I would personally prefer docstrings because I like them better in my editor. Then again, this is @DaKnOb's project, so you should wait for his opinion rather than listen to me :)

**Comment by daknob** [comment]
Hello @stiefel40k and thanks for this PR. While it's good to follow a standard, sometimes it is not so convenient. Your Pull Request is proposing to rename all methods, replace all tabs with four spaces, rearrange some imports, and in general perform a lot of changes.

Let me try to justify some of the decisions made:
- Lines starting with more than one `#` are used similarly to Markdown, to convey chapters / indentation levels. By removing them, while of course not changing the functionality, removes this meaning from the code. 
- Tabs vs spaces is of course a religious war in the developers' land. While I agree 100% that spaces are better, consistent, accurate, etc. you need to configure your editor to convert your tabs to spaces (hitting Tab is ~ 3 times more efficient.. 😄 ) 
- I am not using an IDE with such features so I never benefited from all the automation of such a procedure.
- I'm used to create method names without `_`'s but instead use `camelToe` for methods. Using `_` is probably better, especially in cases like `haveILoggedIn()`, however I was just not used to that.

@j11e Which code formatting do you prefer? The current one or the proposed? Do you use PEP8?

**Comment by j11e** [comment]
I tend to prefer PEP8-style because Python is my main language, so I've gotten used to formatting my code this way. Using `snake_case` is quite unusual these days, but I have no personal preference between that and `camelCase`. All things considered, even though this PR introduces a lot of changes, I'm in favor of merging it (preferably with `"""docstrings"""` instead of comment blocks). If some things slipped through, they can be corrected in the future.

Btw I don't know what editor you use, but SublimeText has an easy way to automatically convert tabs to spaces (and the opposite if you want) and to enforce consistency within files ;)

**Comment by stiefel40k** [comment]
Hi @DaKnOb (and @j11e again)!

Of course it is not mandatory to accept my contribution. I know there was a lot of (formal) changes for one PR.

If you wish I can make an other branch where I only change the block comments to `"""docstrings"""`, and than you'll have the opportunity to include only those changes, if the changes in this PR would be too much for one go.

In the meantime writing this comment I just created that branch. See my other PR #40

**Comment by daknob** [comment]
@stiefel40k : Can you please make this PR compatible with the docstrings so we can merge it? :-) 
Unfortunately I caused some conflicts, but I believe it is easy to reformat. Feel free to either fix this, or close this and open a new PR. 

@j11e I'm a `vim` user :P

**Comment by stiefel40k** [comment]
@DaKnOb : I'll do it as soon as I get home from work. (around 18:00-19:00 CEST)

**Comment by daknob** [comment]
@stiefel40k Perfect! Will merge about an hour later hopefully.

**Comment by stiefel40k** [comment]
So I merged the comments into my master, which holds the changes for this PR. I think, everythink should be fine. I don't know what kind of conflict it has with the torpaste.py, becouse I didn't really change there much.

What I however found, and for this I created a TODO in the filesystem.py, that the os module doesn't include a method `mkdirs` there is an `mkdir` and an `makedirs`. Please check that.

**Comment by j11e** [comment]
To eliminate merge conflicts, the following should work: `git pull upstream master`. Well, that won't solve the conflicts per se, but it will make them appear in your local master branch so that you can fix them!

Note that "upstream" is the standard naming convention, I don't know how you've named your git remote corresponding to this repo.

**Comment by stiefel40k** [comment]
I tried your method, but it didn't work out, so I did it with the good ol' deleted the content of the file, and copied from here, and made my changes, however as I see this couldn't resolve the conflicts.

**edit:** so I managed to eliminate the conflicts, hope I didn't screw it.

**Comment by j11e** [comment]
I don't see conflicts anymore, so I guess you solved the problem ¯_(ツ)_/¯

**Comment by daknob** [comment]
Hmmm, I can see some bad indentation in the docstring commends in `backends/example.py`. Shouldn't all docstrings be exactly 4 spaces indented?

**Comment by daknob** [comment]
So let's agree on something that will probably make this merge faster:

We're switching this project to full PEP8, and we're using docstrings for documentation. Is that correct? If yes, can you open a new PR that does just that in the current `master` branch?
If you open this PR I can merge it and then work on features / `python3` transition, etc.

Thanks a lot!

**Comment by stiefel40k** [comment]
So first of all, you were right regarding the indentation. I fixed that.

Why do you actually want a new PR? I mean this PR does exactly what you say. docstrings+PEP8. Is it the `method_name`-style? Becouse as I checked this naming convention is what from PEP8 comes. Or at least a lot of people say, that this one should be used.

**Review by j11e — APPROVED** [review]

**Comment by daknob** [comment]
Oh, I just asked for a new PR to avoid the git diff bloat, but it shouldn't be a problem. Thanks for this PR!

**Comment by daknob** [comment]
After merging this Pull Request the project did not work. The reason is that while `filesytems/backend.py` was converted to snake_case, the methods were not converted inside `torpaste.py`, which caused them not to work.

**Comment by stiefel40k** [comment]
I'm really sorry about it. Do you want me to fix it? Unfortunatelly there were no tests I could have run to see this :/

**Comment by daknob** [comment]
@stiefel40k Sorry for the lack of tests, I will open an issue and try to work on that some time later. Usually the "test" process is to run TorPaste with `docker` and navigate to the website. It's bad, and we can definitely improve it. Can you pull the current `master`, create a new branch, say `pep`, convert everything to PEP8, and then submit a PR to `DaKnOb:master` from `stiefel40k:pep`?

BTW, which tool do you use for Python to PEP8 conversion?

**Comment by stiefel40k** [comment]
Sure, I'll do it.

I'm using Jetbrains PyCharm IDE. It has a code inspection tool, which helps in the convertion.

**Comment by j11e** [comment]
I'm going to write a quick CONTRIBUTING.md that will contain a testing procedure. We'll update it when we have an actual unit test suite or something similar.

**Comment by daknob** [comment]
@j11e Good idea, was going to do this but you beat me to that.. Pretty busy these days unfortunately.

**Pull request merged**
